### ISSUE TITLE
Assignment 5: Calculator

### ISSUE THREAD

**Issue by ted-devs** [ted-devs/csharp-assignments-amad#8]
You have to create a calculator that can perform the following functionality on `2` variables.
1. Addition
2. Subtraction
3. Division
4. Multiplication
5. Modulus

#### Flow
1. User Inputs Number 1
2. User Inputs Number 2
3. Ask user for the operation you want to perform.
4. Perform the operation and show the result to the user.
5. Ask the user if they want to do another calculation. If user selects yes, repeat the whole process, otherwise stop the program. 

#### Sample Output
![image](https://user-images.githubusercontent.com/61463523/200914814-af352718-f01e-4764-bcbc-c1271d7f53a7.png)

**Comment by ted-devs** [comment]
@Amadkazmi

**Comment by ted-devs** [comment]
I'll add sample output soon.

**Comment by Amadkazmi** [comment]
@ted-devs can you please provide me sample ?

**Comment by ted-devs** [comment]
@Amadkazmi Updated with sample output.

**Comment by ted-devs** [comment]
@Amadkazmi please fix your pull request and merge into this branch, not into your own branch.

**Comment by ted-devs** [comment]
Assignment submitted.
